---

- hosts: gogssrv
  vars: 
    gogs_port: 3000
  tasks:
    - name: Create data directory
      file:
        path: /data 
        state: directory
    - name: Clone gogs repo to /data directory
      git:
        repo: https://github.com/KamilBabayev/gogs_data.git 
        dest: /data/gogs_data
        clone: yes
    - name: Pull docker gogs image
      docker: 
        name: gogs1
        image: gogs/gogs
        pull: always
        ports:
          - '3000:3000'
        volumes:
          - /data/gogs_data:/data
        state: started












